/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author User
 */
public class Interfaz_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz_Principal
     */
    public Interfaz_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEstudiantes = new javax.swing.JTable();
        jbtnCrearUsuario = new javax.swing.JButton();
        jbtnEditarUsuario = new javax.swing.JButton();
        jbtnEliminarUsuario = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 16, 37));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logofisei.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CRUD BASICO EN JAVA ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 310, 50));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 70));

        jtblEstudiantes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jtblEstudiantes.setForeground(new java.awt.Color(153, 153, 153));
        jtblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Direecion", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(jtblEstudiantes);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 150));

        jbtnCrearUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jbtnCrearUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jbtnCrearUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jbtnCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-usuario123.png"))); // NOI18N
        jbtnCrearUsuario.setText("Crear");
        jbtnCrearUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnCrearUsuarioMouseMoved(evt);
            }
        });
        jbtnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnCrearUsuarioMouseExited(evt);
            }
        });
        jPanel2.add(jbtnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, -1));

        jbtnEditarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jbtnEditarUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jbtnEditarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jbtnEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatar-de-usuario123.png"))); // NOI18N
        jbtnEditarUsuario.setText("Editar");
        jbtnEditarUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnEditarUsuarioMouseMoved(evt);
            }
        });
        jbtnEditarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnEditarUsuarioMouseExited(evt);
            }
        });
        jbtnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 110, -1));

        jbtnEliminarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jbtnEliminarUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jbtnEliminarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jbtnEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar-usuario123.png"))); // NOI18N
        jbtnEliminarUsuario.setText("Eliminar");
        jbtnEliminarUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtnEliminarUsuarioMouseMoved(evt);
            }
        });
        jbtnEliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtnEliminarUsuarioMouseExited(evt);
            }
        });
        jPanel2.add(jbtnEliminarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 420, 140, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ESTUDIANTES");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 180, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 467));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnEditarUsuarioActionPerformed

    private void jbtnCrearUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCrearUsuarioMouseMoved
        jbtnCrearUsuario.setBackground(new java.awt.Color(175, 238, 238));
    }//GEN-LAST:event_jbtnCrearUsuarioMouseMoved

    private void jbtnCrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnCrearUsuarioMouseExited
        jbtnCrearUsuario.setBackground(new java.awt.Color(204, 204, 204));
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCrearUsuarioMouseExited

    private void jbtnEditarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEditarUsuarioMouseExited
        jbtnEditarUsuario.setBackground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_jbtnEditarUsuarioMouseExited

    private void jbtnEditarUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEditarUsuarioMouseMoved
        jbtnEditarUsuario.setBackground(new java.awt.Color(175, 238, 238));
    }//GEN-LAST:event_jbtnEditarUsuarioMouseMoved

    private void jbtnEliminarUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEliminarUsuarioMouseMoved
        jbtnEliminarUsuario.setBackground(new java.awt.Color(255, 40, 0));    }//GEN-LAST:event_jbtnEliminarUsuarioMouseMoved

    private void jbtnEliminarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEliminarUsuarioMouseExited
        jbtnEliminarUsuario.setBackground(new java.awt.Color(204, 204, 204));    }//GEN-LAST:event_jbtnEliminarUsuarioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCrearUsuario;
    private javax.swing.JButton jbtnEditarUsuario;
    private javax.swing.JButton jbtnEliminarUsuario;
    private javax.swing.JTable jtblEstudiantes;
    // End of variables declaration//GEN-END:variables
}
